
GET http://localhost:3000/api/categorias

###

GET http://localhost:3000/api/categorias/2

###

POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "Pan seco",
    "protegida": false
}

###

PUT http://localhost:3000/api/categorias/1
Content-Type: application/json

{
    "categoriaid":1,
    "nombre": "Pastel"
}

###

DELETE http://localhost:3000/api/categorias/7